apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaledobject
spec:
  scaleTargetRef:
    name: backend

  pollingInterval: 15
  cooldownPeriod: 10

  minReplicaCount: 2
  maxReplicaCount: 10

  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
