# Namespace
namespace: three-tier

# Frontend
frontend:
  replicaCount: 2

  image:
    repository: aasthakumarii/3tier-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5173
    targetPort: 5173

# Backend
backend:
  replicaCount: 3

  image:
    repository: aasthakumarii/3tier-backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

# PostgreSQL
postgres:

  image:
    repository: postgres
    tag: "16"

  database: authdb

  username: postgres

  password: postgres

  service:
    port: 5432

  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""

# Ingress
ingress:

  enabled: true

  className: haproxy

  host: ""

resources: {}
